export const FETCH_DASHBOARD = 'FETCH_DASHBOARD'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT ='LOGOUT'
export const JOB_APPLY ='JOB_APPLY'
export const FETCH_EVENT = 'FETCH_EVENT'